### ISSUE TITLE
建议通过命令行参数接受压缩包，方便tab补全，手动输入压缩包名字实在是有点。。。

### ISSUE THREAD

**Issue by Wrong-pixel** [AabyssZG/CRC32-Tools#1]
parser = argparse.ArgumentParser()
    parser.add_argument('-z', dest='zip', required=True, help='指定压缩包')
    parser.add_argument('-o', dest='output', help='输出路径')
    args = parser.parse_args()

**Comment by AabyssZG** [comment]
哈哈，感谢师傅的优化
这就去更新版本，打算把几个功能集中到一个脚本里面

**Comment by Wrong-pixel** [comment]
> 哈哈，感谢师傅的优化 这就去更新版本，打算把几个功能集中到一个脚本里面

提交了pr，没注意把仓库删了，但是提交记录还在，可以参考下

**Comment by AabyssZG** [comment]
好的，谢谢师傅
目前整合版已经更新完成，如果有什么问题，欢迎再提issues
